import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/DocumentTemplate/DocumentTemplate.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBars,
  faEllipsisVertical,
  faEnvelope,
} from "@fortawesome/free-solid-svg-icons";

export default function Document() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous"
        ></link>
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <FontAwesomeIcon
            className={styles.icon}
            icon={faBars}
            style={{ fontSize: 32, color: "white" }}
          />
          <div className={styles.logo}>
            <Image
              src="/EasyHandler_Hitam.png"
              alt="logo"
              width={50}
              height={50}
            />
          </div>
          <div className={styles.headerRight}>
            <FontAwesomeIcon
              className={styles.icon2}
              icon={faEnvelope}
              style={{ fontSize: 29, color: "white" }}
            />
          </div>
        </div>
        <div class="row justify-content-end mt-5 me-1">
          <div class="col-2">
            <button
              type="button"
              className={`${styles.create} btn btn-primary`}
            >
              Create template
            </button>
          </div>
        </div>
        <div className={styles.company}>
          <p>Company</p>
        </div>
        <div className={styles.judul}>
          <h2>Document Template</h2>
        </div>
        <div className={styles.content}>
          <h4>Surat Keterangan Kerja</h4>
          <p>
            Informasi bahwa benar pekerja dan sedang aktif<br></br>
            bekerja di perusahaan.
          </p>

          <div class="col-2">
            <button
              type="button"
              className={`${styles.btndownload}`}
              data-bs-dismiss="modal"
            >
              Download
            </button>
          </div>

          <div class="row mt-3 justify-content-end">
            <FontAwesomeIcon
              className={styles.icon3}
              icon={faEllipsisVertical}
              style={{ fontSize: 20 }}
            />
          </div>
        </div>
      </main>

      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"
      ></script>
    </div>
  );
}
